// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg0-N3X28uVOXS8nrWEsgndTZLReQHTww',
    appId: '1:660753873168:web:4842ae6c56fada1f5c0d95',
    messagingSenderId: '660753873168',
    projectId: 'car-project-37757',
    authDomain: 'car-project-37757.firebaseapp.com',
    storageBucket: 'car-project-37757.appspot.com',
    measurementId: 'G-R03QKHBC0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSp5JX1_5DvPkgQ7V1p-3xhWUAbZjc2Jw',
    appId: '1:660753873168:android:4225f9f69962df085c0d95',
    messagingSenderId: '660753873168',
    projectId: 'car-project-37757',
    storageBucket: 'car-project-37757.appspot.com',
  );
}
